name: Graph3D
on:
  # Автозапуск
  schedule: [{cron: "0 0 * * *"}]
  # Ручной запуск
  workflow_dispatch:
  # Команда запуска действия, когда выбираем ветку main.
  push:
    branches:
    - main

# Выполнение кода  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          target_branch: output_Graph3D
          build_dir: dist
          commit_message: Update Graph3D
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
