# Действие на GitHub для создания графика пожирающей змейки.
name: Generate Graph3D

# Период автоматического запуска действие в GitHUB.
on:
  schedule:
      # Каждые 12 часов
    - cron: "0 */12 * * *"

  # Команда позволяет вручную запустить активность.
  workflow_dispatch:
  
  # Команда запуска действия, когда выбираем ветку main.
  push:
    branches:
    - main

# Последовательность запуска действий:
jobs:
  # Сборка:
  build:
    # Тип устройства, на котором будет выполняться сборка
    runs-on: ubuntu-latest

    # Шаги в котором постепенно выполняется действии
        jobs:
          github-metrics:
          runs-on: ubuntu-latest
          environment: 
            name: production
            permissions:
              contents: write
          steps:
          - uses: lowlighter/metrics@latest
            with:
              token: ${{ secrets.METRICS_TOKEN }}

      # Создание вывода статуса о сборке
      - name: Show build status
        run: git status

      # Перемещение сборки в ветку output_Graph3D вывода
      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output_Graph3D
          build_dir: dist
          commit_message: Update Graph3D animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
